GitTagApp/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace GitTagApp.Pages
{
    public class AboutModel : PageModel
    {
        private readonly ILogger<AboutModel> _logger;

        public AboutModel(ILogger<AboutModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

GitTagApp/Pages/CreateTag.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GitTagApp.Entities;
using GitTagApp.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Octokit;
using Octokit.Internal;

namespace GitTagApp.Pages
{
    public class TagModel : PageModel
    {
        public IReadOnlyList<Repository> Repositories { get; set; }
        public IReadOnlyList<Repository> StarredRepos { get; set; } // Pets
        public IReadOnlyList<SelectListItem> RepoOptions { get; set; }

        [BindProperty]
        public string RepoId { get; set; }
        
        [BindProperty]
        public string RepoTag { get; set; }

        [BindProperty]
        public Tag Tag { get; set; }

        [ViewData]
        public string Message { get; set; }
        public bool IsPostSuccess { get; set; }
        
        private readonly ILogger<ErrorModel> _logger;
        

        private readonly ITagService _tagService;

        private readonly IGitRepoTagService _gitRepoTagService;

        public TagModel(ILogger<ErrorModel> logger, ITagService tagService, IGitRepoTagService gitRepoTagService)
        {
            _logger = logger;
            _tagService = tagService;
            _gitRepoTagService = gitRepoTagService;
        }

        public async Task OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                string accessToken = await HttpContext.GetTokenAsync("access_token");
                var github = new GitHubClient(new ProductHeaderValue("AspNetCoreGitHubAuth"), 
                    new InMemoryCredentialStore(new Credentials(accessToken)));
            
                Repositories = await github.Repository.GetAllForCurrent();
            
                StarredRepos = await github.Activity.Starring.GetAllForCurrent();
        
                RepoOptions = StarredRepos.Select(x =>
                    new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.Name
                    }).ToList();
            }
        }

        public void OnPostCreate()
        {
            IsPostSuccess = false;
           
            var tag = new Tag();
            tag.Name = Request.Form["Tag.Name"];
            
            var dbTags = (from t in _tagService.GetAll()
                where t.Name == tag.Name
                select t).ToList();
            
            if (!dbTags.Any()) _tagService.Create(tag);
            
            var relatedTag = (from t in _tagService.GetAll()
                where t.Name == tag.Name
                select t).Single();
            
            var gitRepoTag = new GitRepoTag();
            gitRepoTag.GitRepoId = Convert.ToInt64(Request.Form["RepoId"]);
            gitRepoTag.TagId = relatedTag.Id;
            Message = _gitRepoTagService.CreateRepoTag(gitRepoTag);
        }

        public JsonResult OnGetPopulate(long id)
        {
            return new JsonResult(GetResponse(id));
        }

        public IEnumerable<SelectListItem> GetResponse(long id)
        {
            var query = (from rt in _gitRepoTagService.GetAll()
                join t in _tagService.GetAll() on rt.TagId equals t.Id
                where rt.GitRepoId == id
                select new SelectListItem
                {
                    Value = t.Id.ToString(),
                    Text = t.Name
                });
            return query.ToList();
        }
    }
}

GitTagApp/Pages/DeleteTag.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Castle.Core.Internal;
using GitTagApp.Entities;
using GitTagApp.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Octokit;
using Octokit.Internal;

namespace GitTagApp.Pages
{
    public class DeleteTagModel : PageModel
    {
        public IReadOnlyList<Repository> Repositories { get; set; }
        public IReadOnlyList<Repository> StarredRepos { get; set; } // Pets
        public IReadOnlyList<SelectListItem> RepoOptions { get; set; }
        public IEnumerable<SelectListItem> RepoTagOptions { get; set; }

        [BindProperty]
        public string RepoId { get; set; }
        
        [BindProperty]
        public string RepoTag { get; set; }

        [BindProperty]
        public Tag Tag { get; set; }

        public bool IsPostSuccess { get; set; }
        
        private readonly ILogger<ErrorModel> _logger;

        private readonly ITagService _tagService;

        private readonly IGitRepoTagService _gitRepoTagService;

        public DeleteTagModel(ILogger<ErrorModel> logger, ITagService tagService, IGitRepoTagService gitRepoTagService)
        {
            _logger = logger;
            _tagService = tagService;
            _gitRepoTagService = gitRepoTagService;
        }

        public async Task OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                string accessToken = await HttpContext.GetTokenAsync("access_token");
                var github = new GitHubClient(new ProductHeaderValue("AspNetCoreGitHubAuth"), 
                    new InMemoryCredentialStore(new Credentials(accessToken)));
            
                Repositories = await github.Repository.GetAllForCurrent();
            
                StarredRepos = await github.Activity.Starring.GetAllForCurrent();
        
                RepoOptions = StarredRepos.Select(x =>
                    new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.Name
                    }).ToList();
            }
        }

        public void OnPostDelete()
        {
            IsPostSuccess = false;
            
            var result = _gitRepoTagService.DeleteRepoTag(Convert.ToInt64(Request.Form["RepoId"]),
                Convert.ToInt64(Request.Form["RepoTag"]));
            if (!result.IsNullOrEmpty()) IsPostSuccess = true;
        }
        
        public JsonResult OnGetPopulate(long id)
        {
            return new JsonResult(GetResponse(id));
        }

        public IEnumerable<SelectListItem> GetResponse(long id)
        {
            var query = (from rt in _gitRepoTagService.GetAll()
                join t in _tagService.GetAll() on rt.TagId equals t.Id
                where rt.GitRepoId == id
                select new SelectListItem
                {
                    Value = t.Id.ToString(),
                    Text = t.Name
                });
            return query.ToList();
        }
    }
}

GitTagApp/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace GitTagApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

GitTagApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace GitTagApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

GitTagApp/Pages/List.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using GitTagApp.Entities;
using GitTagApp.Interfaces;
using GitTagApp.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Octokit;
using Octokit.Internal;

namespace GitTagApp.Pages
{
    public class ListModel : PageModel
    {
        public IReadOnlyList<Repository> Repositories { get; set; }
        public IReadOnlyList<Repository> StarredRepos { get; set; }
        public List<GitRepo> GitRepos { get; set; }
        
        private readonly ILogger<ErrorModel> _logger;

        private readonly IGitRepoService _repoService;

        private readonly IUserService _userService;

        private readonly ITagService _tagService;

        private readonly IGitRepoTagService _gitRepoTagService;

        public ListModel(ILogger<ErrorModel> logger, IGitRepoService repoService, IUserService userService, ITagService tagService, IGitRepoTagService gitRepoTagService)
        {
            _logger = logger;
            _repoService = repoService;
            _userService = userService;
            _tagService = tagService;
            _gitRepoTagService = gitRepoTagService;
        }

        public async Task OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                var outRepos = new List<GitRepo>();
                var gitName = string.Empty;
                string accessToken = await HttpContext.GetTokenAsync("access_token");
                var github = new GitHubClient(new ProductHeaderValue("AspNetCoreGitHubAuth"), 
                    new InMemoryCredentialStore(new Credentials(accessToken)));
            
                Repositories = await github.Repository.GetAllForCurrent();
            
                StarredRepos = await github.Activity.Starring.GetAllForCurrent();
            
                var tempUser = await github.User.Get(Repositories[0].Owner.Login);
                gitName = tempUser.Name;
                            
                var dbUser = new Entities.User
                {
                    Id = Repositories[0].Owner.Id,
                    Name = gitName
                };
                _userService.Create(dbUser);
                
                foreach (var repo in StarredRepos)
                {
                    var dbRepo = new GitRepo
                    {
                        Id = repo.Id,
                        Name = repo.Name,
                        Description = repo.Description,
                        HttpUrl = repo.HtmlUrl,
                        UserId = dbUser.Id,
                    };
                    _repoService.Create(dbRepo);
                    
                    var repoBuilder = new RepoBuilder(_userService, _tagService, _gitRepoTagService);
                    var outputRepo = repoBuilder.GetPayload(dbRepo);
                    outRepos.Add(outputRepo);
                }

                GitRepos = outRepos;
            }
        }
    }
}

GitTagApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace GitTagApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

GitTagApp/Pages/Tag.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Castle.Core.Internal;
using GitTagApp.Entities;
using GitTagApp.Interfaces;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Razor.Language;
using Microsoft.Extensions.Logging;
using Octokit;
using Octokit.Internal;

namespace GitTagApp.Pages
{
    public class TagModel : PageModel
    {
        public IReadOnlyList<Repository> Repositories { get; set; }
        public IReadOnlyList<Repository> StarredRepos { get; set; }
        
        [BindProperty]
        public Tag Tag { get; set; }
        public List<SelectListItem> RepoOptions { get; set; }
        public List<SelectListItem> TagOptions { get; set; }
        
        [ViewData]
        public string Message { get; set; }
        public bool IsPostSuccess { get; set; }
        
        private readonly ILogger<ErrorModel> _logger;

        private readonly IGitRepoService _repoService;

        private readonly IUserService _userService;

        private readonly ITagService _tagService;

        private readonly IGitRepoTagService _gitRepoTagService;

        public TagModel(ILogger<ErrorModel> logger, IGitRepoService repoService, IUserService userService, ITagService tagService, IGitRepoTagService gitRepoTagService)
        {
            _logger = logger;
            _repoService = repoService;
            _userService = userService;
            _tagService = tagService;
            _gitRepoTagService = gitRepoTagService;
        }

        public async Task OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                var gitName = string.Empty;
                string accessToken = await HttpContext.GetTokenAsync("access_token");
                var github = new GitHubClient(new ProductHeaderValue("AspNetCoreGitHubAuth"), 
                    new InMemoryCredentialStore(new Credentials(accessToken)));
            
                Repositories = await github.Repository.GetAllForCurrent();
            
                StarredRepos = await github.Activity.Starring.GetAllForCurrent();

                RepoOptions = StarredRepos.Select(x =>
                    new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.Name
                    }).ToList();
                
                TagOptions = _tagService.GetAll().Select(x =>
                    new SelectListItem
                    {
                        Value = x.Id.ToString(),
                        Text = x.Name
                    }).ToList();
            }
        }

        public void OnPostCreate()
        {
            IsPostSuccess = false;
            
            var tag = new Tag();
            tag.Name = Request.Form["Tag.Name"];
            
            var dbTags = (from t in _tagService.GetAll()
                where t.Name == tag.Name
                select t).ToList();
            
            if (!dbTags.Any()) _tagService.Create(tag);
            
            var relatedTag = (from t in _tagService.GetAll()
                where t.Name == tag.Name
                select t).Single();
            
            var gitRepoTag = new GitRepoTag();
            gitRepoTag.GitRepoId = Convert.ToInt64(Request.Form["starredRepoId"]);
            gitRepoTag.TagId = relatedTag.Id;
            Message = _gitRepoTagService.CreateRepoTag(gitRepoTag);
        }

        public void OnPostUpdate()
        {
            IsPostSuccess = false;
            var newTag = new Tag();
            
            newTag.Name = Request.Form["Tag.Name"]; // New tag name (from text input)
            var selectedTag = Convert.ToInt64(Request.Form["tagId"]); // Selected from select (tag to be updated)
            newTag.Id = selectedTag;
            var result = _tagService.Update(newTag);

            if (!result.IsNullOrEmpty()) IsPostSuccess = true;

            RedirectToPage("/List");
        }

        public void OnPostDelete(long id)
        {
            IsPostSuccess = false;

            var result = _gitRepoTagService.DeleteRepoTag(Convert.ToInt64(Request.Form["starredRepoId"]), Convert.ToInt64(Request.Form["tagId"]));

            if (!result.IsNullOrEmpty()) IsPostSuccess = true;
        }
    }
}

GitTagApp/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h1 class="text-black-50" style="border-bottom: 1px solid #95999c; margin-bottom: 1rem;">@ViewData["Title"]</h1>

<h4 class="text-black-50">Scope</h4>

<p>
    This app was developed to make it easier for Github users to find starred repositories.
    The app fetches the repositories starred by the user and allows the user to add tags to those repositories.
    The user can also search repositories by tags, edit and delete tags.
</p>

<h4 class="text-black-50">Technologies</h4>

<p>
    The app was developed using .NET Core with Razor Pages.
    Github sign-in was done using Oauth 2.
</p>

<div class="container-fluid">
    <img src="images/768px-.NET_Core_Logo.svg.png" style="height: 20%; width: 20%;"/>
    <img src="images/oauth2-640x410.jpg" style="height: 35%; width: 35%;" />
    <img src="images/GitHub-Mark-120px-plus.png" />
</div>

GitTagApp/Pages/CreateTag.cshtml
@page "{id?}"
@model TagModel
@{
    ViewData["Title"] = "Create Tags";
}

@if (!User.Identity.IsAuthenticated)
    {
        <div class="row" style="display: block; align-content: center; justify-content: center; margin: 2rem;">
            <h1 class="text-black-50">Welcome to GitTagApp</h1>
            <p>Please log in to access full functionalities:</p>
            <a asp-action="Login" asp-controller="Login" class="btn btn-primary">Log In with GitHub</a>
        </div>
    }
 else
 {
     <h1 class="text-black-50">
         Create Tags
     </h1>
     <p>
         Here, we can add tags to your starred repositories.
         Tags will make it easier to find repositories, allowing search by tag funcionality.
         Just add the desired tags and be happy!<br>
         To create new tags, just click on <strong>Add tags</strong> button, fill the form and voila!<br>
     </p>

     <div id="accordion" class="container-fluid">
         <div class="card">
             <div class="card-header">
                 <h5 class="mb-0">
                     <button class="btn btn-primary" data-toggle="collapse" data-target="#collapse-create" aria-expanded="true" aria-controls="collapse-create">
                         Add tags
                     </button>
                 </h5>
             </div>
             <div id="collapse-create" class="collapse show" aria-labelledby="heading-1" data-parent="#accordion">
                 <div class="card-body" id="card-1">
                     <form class="form-horizontal" asp-page-handler="create" method="post" style="padding-left: 10px; margin: 10px; width: 90%; height: 65px;; display: flex; justify-content: space-evenly; align-items: baseline;">
                         <div class="form-group">
                             <label asp-for="Repositories" class="custom-control-label" style="margin: 3px; font-size: 16px; color: #4e555b; position: relative">
                                 Repository:
                             </label>
                             <div class="col-sm-10">
                                 <select asp-for="RepoId" asp-items="Model.RepoOptions" style="margin-top: 3px;; border-radius: 0.3rem; border: 1px solid #95999c; color: #4e555b; width: 10rem; height: 2rem;">
                                    <option value="">--Select--</option>
                                 </select>
                             </div>
                         </div>
                         <div class="form-group">
                             <label asp-for="Tag" class="custom-control-label" style="margin: 3px; font-size: 16px; color: #4e555b;">
                                 Enter tag name:
                             </label>
                             <div class="col-sm-10">
                                 <input type="text" class="form-control" asp-for="Tag.Name" style="height: 2rem; border-radius: 0.3rem; border: 1px solid #95999c;margin: 3px;;"/><br/>
                             </div>
                         </div>
                         <div class="form-group">
                             <div class="col-sm-offset-2 col-sm-10">
                                 <button id="btn-create" class="btn btn-primary" name="create" type="submit" style="height: 3rem; width: auto; margin-top: 10px; align-items: center; justify-content: center">
                                     Save
                                 </button>
                             </div>
                         </div>
                     </form>
                 </div>
             </div>
         </div>
     </div>
 }

@section scripts {
    <script>
        let tagsSelect = document.getElementById('RepoTag');
                $('#RepoId').val('');
        
                $('#RepoId').change(function () {
        
                    const repoId = $(this).val();
                    clearTagsSelect();
        
                    if (repoId === '') {
                        return;
                    }                   
                   
                        fetch('https://localhost:5001/CreateTag/' + repoId + '?handler=populate')
                                .then(response => response.json())
                                .then(data => {
                                    let option;
                
                                    for (let i = 0; i < data.length; i++) {
                                        option = document.createElement('option');
                                        option.text = data[i].text;
                                        option.value = data[i].value;
                                        tagsSelect.add(option);
                                    }
                                });
                  
                });

        function clearTagsSelect() {
            $('#RepoTag')
                .find('option')
                .remove()
                .end()
                .append('<option value="">--Select--</option>')
                .val('');
        }
    </script>

}

GitTagApp/Pages/DeleteTag.cshtml
@page "{id?}"
@model DeleteTagModel
@{
    ViewData["Title"] = "Delete Tags";
}

@if (!User.Identity.IsAuthenticated)
{
    <div class="row" style="display: block; align-content: center; justify-content: center; margin: 2rem;">
        <h1 class="text-black-50">Welcome to GitTagApp</h1>
        <p>Please log in to access full functionalities:</p>
        <a asp-action="Login" asp-controller="Login" class="btn btn-primary">Log In with GitHub</a>
    </div>
}
else
{
    <h1 class="text-black-50">
        Delete Tags
    </h1>
    <p>
        Here, we can remove tags from starred repositories. Tags will make it easier to find
        repositories, allowing search by tag funcionality. <br>
        To delete tags, just click on Delete tags button and select the tag to remove. This will only delete
        the tag for the selected repository.<br>
    </p>

    <div id="accordion" class="container-fluid">
        <div class="card">
             <div class="card-header" id="heading-3">
                 <h5 class="mb-0">
                     <button class="btn btn-primary collapsed" data-toggle="collapse" data-target="#collapse-delete" aria-expanded="false" aria-controls="collapse-delete">
                         Delete tags
                     </button>
                 </h5>
             </div>
             <div id="collapse-delete" class="collapse" aria-labelledby="heading" data-parent="#accordion">
                 <div class="card-body">
                     <form class="form-horizontal" asp-page-handler="delete" method="post" style="padding-left: 10px; margin: 10px; width: 90%; height: 65px;; display: flex; justify-content: space-evenly; align-items: baseline;">
                         <div class="form-group">
                             <label asp-for="Repositories" class="custom-control-label" style="margin: 3px; font-size: 16px; color: #4e555b; position: relative">
                                 Repository:
                             </label>
                             <div class="col-sm-10">
                                 <select asp-for="RepoId" asp-items="Model.RepoOptions" style="margin-top: 3px;; border-radius: 0.3rem; border: 1px solid #95999c; color: #4e555b; width: 10rem; height: 2rem;">
                                        <option value="">--Select--</option>
                                 </select>
                             </div>
                         </div>
                         <div class="form-group">
                             <label asp-for="Tag" class="custom-control-label" style="margin: 3px; font-size: 16px; color: #4e555b;">
                                 Tag:
                             </label>
                             <div class="col-sm-10">
                                 <select id="RepoTag" name="RepoTag" style="margin-top: 3px;; border-radius: 0.3rem; border: 1px solid #95999c; color: #4e555b; width: 10rem; height: 2rem;">
                                        <option value="">--Select--</option>
                                 </select>
                             </div>
                         </div>
                         <div class="form-group">
                             <div class="col-sm-offset-2 col-sm-10">
                                 <button id="btn-delete" class="btn btn-primary" type="submit" style="height: 3rem; width: auto; margin-top: 10px; align-items: center; justify-content: center; ">
                                     Delete
                                 </button>
                             </div>
                         </div>
                     </form>
                 </div>
             </div>
         </div>
     </div>
 }

@section scripts {
    <script>
        let tagsSelect = document.getElementById('RepoTag');
                $('#RepoId').val('');
        
                $('#RepoId').change(function () {
        
                    const repoId = $(this).val();
                    clearTagsSelect();
        
                    if (repoId === '') {
                        return;
                    }                   
                   
                        fetch('https://localhost:5001/DeleteTag/' + repoId + '?handler=populate')
                                .then(response => response.json())
                                .then(data => {
                                    let option;
                
                                    for (let i = 0; i < data.length; i++) {
                                        option = document.createElement('option');
                                        option.text = data[i].text;
                                        option.value = data[i].value;
                                        tagsSelect.add(option);
                                    }
                                });
                  
                });

        function clearTagsSelect() {
            $('#RepoTag')
                .find('option')
                .remove()
                .end()
                .append('<option value="">--Select--</option>')
                .val('');
        }
    </script>

}

GitTagApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="flex-column">
     @if (!User.Identity.IsAuthenticated)
    {
        <div class="row" style="display: block; align-content: center; justify-content: center; margin: 2rem;">
            <h1 class="text-black-50">Welcome to GitTagApp</h1>
            <p>Please log in to access full functionalities:</p>
            <a asp-action="Login" asp-controller="Login" class="btn btn-primary">Log In with GitHub</a>
        </div>
    }
     else
     {
         <div class="row" style="display: flex; align-content: center; justify-content: center;">
             <h1 class="text-black-50">Welcome to GitTagApp</h1>
             <p style="max-width: 80%; padding: 2rem; justify-content: center; position: relative;">
                 Here you can list starred repos, add tags, and search starred repositories by tag.
                 To navigate the app, just use the top menu bar.
             </p>
         </div>
     }
</div>

GitTagApp/Pages/List.cshtml
@page
@model ListModel
@{
    ViewData["Title"] = "List";
}

 @if (!User.Identity.IsAuthenticated)
    {
        <div class="row" style="display: block; align-content: center; justify-content: center; margin: 2rem;">
            <h1 class="text-black-50">Welcome to GitTagApp</h1>
            <p>Please log in to access full functionalities:</p>
            <a asp-action="Login" asp-controller="Login" class="btn btn-primary">Log In with GitHub</a>
        </div>
    }
 else
 {
     <h1 class="text-black-50">
         List
     </h1>
     <p>
         Here, we can list both all repositories and starred repositories.
         The list also shows associated tags added to each of the starred repositories.
     </p>

     <div class="container-fluid" id="accordion">
         <div class="card">
             <div class="card-header" id="heading-1">
                 <h5 class="mb-0">
                     <button class="btn btn-primary collapsed" data-toggle="collapse" data-target="#collapse-repos" aria-expanded="false" aria-controls="collapse-repos">
                         Repositories
                     </button>
                 </h5>
             </div>
             <div id="collapse-repos" class="collapse show" aria-labelledby="heading-1" data-parent="#accordion">
                 <div class="card-body">
                     <ul>
                         @foreach (var repo in Model.Repositories)
                         {
                             <li><a href="@repo.HtmlUrl">@repo.FullName</a></li>
                         }
                     </ul>
                 </div>
             </div>
         </div>
         <div class="card">
             <div class="card-header" id="heading-2">
                 <h5 class="mb-0">
                     <button class="btn btn-primary collapsed" data-toggle="collapse" data-target="#collapse-starred" aria-expanded="false" aria-controls="collapse-starred">
                         Starred Repositories
                     </button>
                 </h5>
             </div>
             <div id="collapse-starred" class="collapse" aria-labelledby="heading-2" data-parent="#accordion">
                 <div class="card-body">
                     <ul>
                         @foreach (var repo in Model.GitRepos)
                         {
                             <li>Name: <a href="@repo.HttpUrl">@repo.Name</a></li>
                             <li>Id: @repo.Id</li>
                             <li>Description: @repo.Description</li>
                             <li>URL: @repo.HttpUrl</li>
                             <li>Tags: @foreach (var item in repo.GitRepoTags)
                              {
                                  <li>@item.Tag.Name</li>
                              }
                            </li>
                         <br>
                         }
                     </ul>
                 </div>
             </div>
         </div>
     </div>
 }